---
title: "Meetings Weekly Schedule 2020"
date: "Last Updated `r format(Sys.time(), '%d %B, %Y')`"
output: github_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
					  warning = FALSE, 
					  message = FALSE,
					  fig.align = "center")
```


```{r Setup_Libraries}
library(tidyverse)
library(pander)
```

```{r get_Schedule}
cp <- paste(
    "Weekly Schedule of Meetings for the Bioinformatics Hub. Meetings are now held using Zoom"
    )

wkly_sched <- read_csv("WeeklyMeetings.csv", col_types = cols(Date=col_date())) %>%
  dplyr::select(Date,"Meeting Type", Who, Group) %>%
  replace_na(list(Who = " ",Group = " "))

groups <- read_csv("WeeklyMeetings.csv") %>%
  dplyr::select("Group A","Group B","Group C")

grp_members <- list("Group A" = (na.omit(groups$"Group A")), "Group B" = (na.omit(groups$"Group B")), "Group C" =(na.omit(groups$"Group C")))

grp_members %>%
  pander::pander()

wkly_sched %>%
  pander::pander(caption = cp, style="multiline", split.table = Inf)
```

