---
title: "Meetings Weekly Schedule 2020"
author: "Mark Armstrong"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: 
    code_folding: hide
    toc: yes
    toc_depth: 4
    toc_float: yes
    fig_caption: yes
    fig_width: 8
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
					  warning = FALSE, 
					  message = FALSE,
					  fig.align = "center")
```


```{r Setup_Libraries}
library(tidyverse)
library(readxl)
library(pander)
```

```{r get_Schedule}
cp <- paste(
    "Weekly Schedule of Meetings for the Bioinformatics Hub. Meetings are held the The Braggs 3.13/3.14 from 2:00pm to 3:30pm, except for the following dates: 26/03 & 09/04 from 4:00pm to 5:30pm and 16/04 from 12:00pm to 1:30pm."
    )

wkly_sched <- read_csv("WeeklyMeetings.csv", col_types = cols(Date=col_date())) %>%
  rename(" " = "X5") %>%
  replace_na(list(Who = " ",Group = " ", 'Group A' = " ", 'Group B' = " ", 'Group C' = " ", ' ' = "|")) 

wkly_sched %>%
  pander(caption = cp, style="multiline", split.table = Inf)

```

